name: ''
debug: true

log: 
  loggers:
  - name: 'runtime'
    level: debug
    writers: text
  writers:
    - name: text
      type: console
      layout: '[{L}]{T}: {M} - {F:S}{N}'
      options:
        colorized: true